---
server:
  port: 8081
  contextPath: /SpringBootKafka
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hbm2ddl.method: update
    show_sql: true
    format_sql: true
    dialect: org.hibernate.dialect.MySQLDialect
    jpa:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/websystique
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    jpa:
      hbm2ddl.method: create-update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

 
     

